name: InssUtils Workflow

on:
  push:
    branches:
      - main
      - develop

    tags:
      - '*'

  pull_request:
    branches:
      - main
      - develop

  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}

      # Upload an artifact when a tag is pushed, or a new release is created with GitHub.
      - name: Upload artifact
        if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'release' && github.event.action == 'created')
        uses: actions/upload-artifact@v2
        with:
          name: InssUtils
          path: build/libs/InssUtils.jar
